In [21]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
# Importing the dataset

dataset = pd.read_csv('/Users/sahitya/Desktop/Untitled Folder/Affairs.csv')
dataset.head()

Unnamed: 0  naffairs  kids  vryunhap  unhap  avgmarr  hapavg  vryhap  \
0           1         0     0         0      0        0       1       0   
1           2         0     0         0      0        0       1       0   
2           3         3     0         0      0        0       1       0   
3           4         0     1         0      0        0       1       0   
4           5         3     1         0      0        0       0       1   

   antirel  notrel  slghtrel  smerel  vryrel  yrsmarr1  yrsmarr2  yrsmarr3  \
0        0       0         1       0       0         0         0         0   
1        0       0         0       1       0         0         0         1   
2        0       0         1       0       0         0         1         0   
3        1       0         0       0       0         0         0         0   
4        0       0         1       0       0         0         0         1   

   yrsmarr4  yrsmarr5  yrsmarr6  
0         0         1         0  
1         0         0         0  
2         0         0         0  
3         0         0         1  
4         0         0         0

In [23]:
#creating bins and encoding 

bins = [-10, 0 , 25]
labels =[0,1]
dataset['naffairs'] = pd.cut(dataset['naffairs'], bins, labels = labels)

In [24]:
# Specifying independent and dependent variables

Y = dataset.naffairs

X = dataset.drop(['naffairs'], axis = 1)

In [25]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

print(X_train)
print(y_train)
print(X_test)
print(y_test)


     Unnamed: 0  kids  vryunhap  unhap  avgmarr  hapavg  vryhap  antirel  \
120         121     0         0      0        1       0       0        0   
277         278     0         0      0        0       0       1        1   
108         109     1         0      0        1       0       0        0   
569         570     1         0      0        0       1       0        0   
361         362     1         0      0        0       0       1        0   
..          ...   ...       ...    ...      ...     ...     ...      ...   
339         340     1         0      0        0       0       1        0   
477         478     1         0      0        0       0       1        0   
200         201     1         0      0        0       1       0        0   
398         399     0         0      0        0       0       1        0   
164         165     0         0      0        0       0       1        0   

     notrel  slghtrel  smerel  vryrel  yrsmarr1  yrsmarr2  yrsmarr3  yrsmarr4  \
120   

In [26]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Logistic Regression

In [27]:
#Training the model

from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression(random_state = 0)
logistic_classifier.fit(X_train, y_train)

# Predicting the Test set results

y_pred = logistic_classifier.predict(X_test)

#making the condusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[89  4]
 [24  4]]


/Users/sahitya/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [29]:
accuracy = (89 + 4)/(89+4+24+4)
print(accuracy)

0.768595041322314


Accuracy = 0.768

# K nearest neighbours 

In [30]:
# Training the K-NN model on the Training set

from sklearn.neighbors import KNeighborsClassifier
KNN_classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN_classifier.fit(X_train, y_train)

# Predicting the Test set results

KNN_y_pred = KNN_classifier.predict(X_test)

#making the condusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, KNN_y_pred)
print(cm)


[[80 13]
 [25  3]]


In [31]:
accuracy = (80 + 3)/(80 + 13 + 25+3)
print(accuracy)

0.6859504132231405


Accuracy = 0.685

# SVM

In [32]:
# Training the SVM model on the Training set

from sklearn.svm import SVC
SVC_classifier = SVC(kernel = 'linear', random_state = 0)
SVC_classifier.fit(X_train, y_train)

# Predicting the Test set results

SVC_y_pred = SVC_classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, SVC_y_pred)
print(cm)


[[83 10]
 [21  7]]


In [33]:
accuracy = (83+7)/(83+10+21+7)
print(accuracy)

0.743801652892562


Accuracy = 0.743

# Kernal SVM

In [34]:
# Training the Kernel SVM model on the Training set

from sklearn.svm import SVC
rbf_classifier = SVC(kernel = 'rbf', random_state = 0)
rbf_classifier.fit(X_train, y_train)

# Predicting the Test set results

rbf_y_pred = rbf_classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, rbf_y_pred)
print(cm)


[[92  1]
 [25  3]]


In [35]:
accuracy = (92+3)/(92+1+25+3)
print(accuracy)

0.7851239669421488


Accuracy = 0.785

# Naive Bayes classification

In [37]:
# Training the Naive Bayes model on the Training set

from sklearn.naive_bayes import GaussianNB
NB_classifier = GaussianNB()
NB_classifier.fit(X_train, y_train)

# Predicting the Test set results

NB_y_pred = NB_classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, NB_y_pred)
print(cm)


[[67 26]
 [18 10]]


In [38]:
accuracy = (67+10)/(67+26+18+10)
print(accuracy)

0.6363636363636364


Accuracy = 0.636

# Decision tree

In [39]:
# Training the Decision Tree Classification model on the Training set

from sklearn.tree import DecisionTreeClassifier
DT_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DT_classifier.fit(X_train, y_train)

# Predicting the Test set results

DT_y_pred = DT_classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, DT_y_pred)
print(cm)



[[71 22]
 [19  9]]


In [40]:
accuracy = (71+9)/(71+22+19+9)
print(accuracy)

0.6611570247933884


Accuracy = 0.661

# Random Forest

In [41]:
# Training the Random Forest Classification model on the Training set

from sklearn.ensemble import RandomForestClassifier
RF_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
RF_classifier.fit(X_train, y_train)

# Predicting the Test set results

RF_y_pred = RF_classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, RF_y_pred)
print(cm)


[[78 15]
 [20  8]]


In [42]:
accuracy = (78+8)/(78+15+20+8)
print(accuracy)

0.7107438016528925


Accuracy = 0.710